### ISSUE TITLE
Error when generating

### ISSUE THREAD

**Issue by MomchilovP** [javiorfo/nvim-springtime#1]
Hello I just installed this plugin in my lazyvim config, and everything works perfectly up until the moment when I need to generate a project. After confirming the generation I get a ton of errors from the "generator" of the plugin. When I check the logs, nothing of use really shows there. I can provide an image with the error if needed.

**Comment by javiorfo** [comment]
Hello,
If you send me an image will be fine.

Also will be helpful if you enable the logger debug with this (Lazy.nvim):
```lua
opts = {
        internal = {
            log_debug = true
        }
    }
```

Then you can generate a project and send the results you see executing `:SpringtimeLogs`. All the log (including the DEBUG) is a great help.

**Comment by Olprog59** [comment]
Hello,
Same problem : 
```
E5108: Error executing lua ...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:27: attempt to concatenate local 'result' (a table value)
stack traceback:
	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:27: in function 'split'
	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:34: in function 'validate_dependencies'
	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:112: in function 'create_project'
	.../share/nvim/lazy/nvim-springtime/lua/springtime/core.lua:137: in function 'generate'
	...al/share/nvim/lazy/nvim-springtime/lua/springtime/ui.lua:128: in function 'callback'
	.../sam/.local/share/nvim/lazy/nvim-popcorn/lua/popcorn.lua:60: in function 'execute_callback'
	[string ":lua"]:1: in main chunk
```

**Comment by javiorfo** [comment]
> Hello, Same problem :
> 
> ```
> E5108: Error executing lua ...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:27: attempt to concatenate local 'result' (a table value)
> stack traceback:
> 	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:27: in function 'split'
> 	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:34: in function 'validate_dependencies'
> 	...e/nvim/lazy/nvim-springtime/lua/springtime/generator.lua:112: in function 'create_project'
> 	.../share/nvim/lazy/nvim-springtime/lua/springtime/core.lua:137: in function 'generate'
> 	...al/share/nvim/lazy/nvim-springtime/lua/springtime/ui.lua:128: in function 'callback'
> 	.../sam/.local/share/nvim/lazy/nvim-popcorn/lua/popcorn.lua:60: in function 'execute_callback'
> 	[string ":lua"]:1: in main chunk
> ```

Hello,
You were right about the problem.
I have fixed it and made a new release. [Fix](https://github.com/javiorfo/nvim-springtime/commit/e62938e18c892e5905a31f8c0d75bbc1514e6f62)

Execute a lazy.nvim update and test it again.

Thanks!

**Comment by Olprog59** [comment]
Thanks, but a new bug:
[ERROR][06/26/2024 22:28:02]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:28:02]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:28:03]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 70 56872   70 39830    0     0  46930      0  0:00:01 --:--:--  0:00:01 46914
100 56872  100 56872    0     0  66305      0 --:--:-- --:--:-- --:--:-- 66284
[ERROR][06/26/2024 22:28:03]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:28:03]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:28:04]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 56872  100 56872    0     0  95315      0 --:--:-- --:--:-- --:--:-- 95422
[ERROR][06/26/2024 22:28:04]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:28:04]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:28:04]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 75 56872   75 43082    0     0  75006      0 --:--:-- --:--:-- --:--:-- 74925
100 56872  100 56872    0     0  97818      0 --:--:-- --:--:-- --:--:-- 97718
[ERROR][06/26/2024 22:29:37]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:29:37]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:29:38]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 56872  100 56872    0     0   118k      0 --:--:-- --:--:-- --:--:--  118k
[ERROR][06/26/2024 22:29:38]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:29:38]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:29:38]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 78 56872   78 44451    0     0  67189      0 --:--:-- --:--:-- --:--:-- 67146
100 56872  100 56872    0     0  85068      0 --:--:-- --:--:-- --:--:-- 85010
[ERROR][06/26/2024 22:29:38]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[ERROR][06/26/2024 22:29:38]: Dload  Upload   Total   Spent    Left  Speed
[ERROR][06/26/2024 22:29:39]: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 56872  100 56872    0     0   184k      0 --:--:-- --:--:-- --:--:--  185k

**Comment by javiorfo** [comment]
> Thanks, but a new bug: [ERROR][06/26/2024 22:28:02]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:28:02]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:28:03]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 70 56872 70 39830 0 0 46930 0 0:00:01 --:--:-- 0:00:01 46914 100 56872 100 56872 0 0 66305 0 --:--:-- --:--:-- --:--:-- 66284 [ERROR][06/26/2024 22:28:03]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:28:03]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:28:04]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 56872 100 56872 0 0 95315 0 --:--:-- --:--:-- --:--:-- 95422 [ERROR][06/26/2024 22:28:04]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:28:04]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:28:04]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 75 56872 75 43082 0 0 75006 0 --:--:-- --:--:-- --:--:-- 74925 100 56872 100 56872 0 0 97818 0 --:--:-- --:--:-- --:--:-- 97718 [ERROR][06/26/2024 22:29:37]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:29:37]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:29:38]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 56872 100 56872 0 0 118k 0 --:--:-- --:--:-- --:--:-- 118k [ERROR][06/26/2024 22:29:38]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:29:38]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:29:38]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 78 56872 78 44451 0 0 67189 0 --:--:-- --:--:-- --:--:-- 67146 100 56872 100 56872 0 0 85068 0 --:--:-- --:--:-- --:--:-- 85010 [ERROR][06/26/2024 22:29:38]: % Total % Received % Xferd Average Speed Time Time Time Current [ERROR][06/26/2024 22:29:38]: Dload Upload Total Spent Left Speed [ERROR][06/26/2024 22:29:39]: 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 56872 100 56872 0 0 184k 0 --:--:-- --:--:-- --:--:-- 185k

Those are curl info logs, not errors (I have to check why they are logged as errors).
Have you been able to generate a project?
If not, let me know which options have you selected

**Comment by Olprog59** [comment]
I chose Maven and Java 22. 

Then the Dependencies: devtools, lombok, web, data-jpa, mysql

**Comment by javiorfo** [comment]
> I chose Maven and Java 22.
> 
> Then the Dependencies: devtools, lombok, web, data-jpa, mysql

I assume this is because the spaces between the comma and the next library:
`devtools, lombok, web, data-jpa, mysql`

If you don't press space after select every library I will work correctly:
`devtools,lombok,web,data-jpa,mysql`

Anyway I'm going to make a change and remove all possible spaces so this will not be a problem anymore

**Comment by javiorfo** [comment]
@Olprog59 @MomchilovP 

Execute a lazy.nvim update and try again (There is no more problems with spaces in between libraries)

**Comment by Olprog59** [comment]
@javiorfo 
Sorry, I'm in France. I wasn't able to reply before.
I've just tested and I still have an error. The same as yesterday with curl. 
<img width="599" alt="CleanShot 2024-06-27 at 13 16 32@2x" src="https://github.com/javiorfo/nvim-springtime/assets/26999116/e3da0453-601f-4677-9ff6-b916e14018a1">
<img width="800" alt="CleanShot 2024-06-27 at 13 16 49@2x" src="https://github.com/javiorfo/nvim-springtime/assets/26999116/b8b1e676-6a1d-47a9-899e-3fbfb581b1d7">

**Comment by javiorfo** [comment]
> @javiorfo Sorry, I'm in France. I wasn't able to reply before. I've just tested and I still have an error. The same as yesterday with curl. <img alt="CleanShot 2024-06-27 at 13 16 32@2x" width="599" src="https://private-user-images.githubusercontent.com/26999116/343749678-e3da0453-601f-4677-9ff6-b916e14018a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODk4NzAsIm5iZiI6MTcxOTQ4OTU3MCwicGF0aCI6Ii8yNjk5OTExNi8zNDM3NDk2NzgtZTNkYTA0NTMtNjAxZi00Njc3LTlmZjYtYjkxNmUxNDAxOGExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExNTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MGEzZmIyMDc1MmJkMDNmM2YyNGFiM2M4N2JjOWI3NWVkMGI4NTBkZTU2ZGRkMGVjNjRhMmEyZTk5N2U2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JUk3iBJUS6ZEPxDZdso1RCR0L9p1thEJjmEIZr0APDw"> <img alt="CleanShot 2024-06-27 at 13 16 49@2x" width="800" src="https://private-user-images.githubusercontent.com/26999116/343749681-b8b1e676-6a1d-47a9-899e-3fbfb581b1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0ODk4NzAsIm5iZiI6MTcxOTQ4OTU3MCwicGF0aCI6Ii8yNjk5OTExNi8zNDM3NDk2ODEtYjhiMWU2NzYtNmExZC00N2E5LTg5OWUtM2ZiZmI1ODFiMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDExNTkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNmY3MmEwN2ZhNTE5MmZhYTVjNGIwY2QxY2M5NDg5YmQzNjU5NjZhNmNhNjRhNDZhNTVjNWZiZDE3OTMwNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F3MODDX98j5LIzROXkxlM-ZDAjMCuQFcCBs9ITSm9X0">

I tried the same and I was able to generate the project.
I wonder if there is a problem on superposition in nvim windows. I see you are using telescope cmd.
Maybe the prompt as popup is generating some error. 
Try disabling the confirmation dialog:
```lua
-- lazy.nvim
opts = {
        dialog = {
            confirmation = false,
        }
}
```

**Comment by Olprog59** [comment]
@javiorfo 
Yes, it works. I do have the zip. It unzipped properly.
Because curl's logs, there are errors.

Thank you very much for your plugin.
